# Generated by Django 5.1.6 on 2025-02-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="user",
            new_name="following",
        ),
    ]
